index:
    path: /
    controller: App\Controller\HomeController::index

security_login:
    path: /login
    controller: App\Controller\SecurityController::login

security_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

register:
    path: /register
    controller: App\Controller\RegistrationController::registerAction

team_create:
    path: /team/create
    controller: App\Controller\TeamController::createaction

team_join:
    path: /team/join/
    controller: App\Controller\TeamController::joinAction